Reidcrews signoff location
lchapman42/Control-Sensing-Wireless-Charging-Robot pull request #3
Opened 2023-10-30 18:22 UTC by reidcrews

2023-11-05 18:04 UTC, n37chen requested changes
This is a relatively small signup. It may be good to combine it with other signups.

2023-11-05 18:04 UTC, n37chen commented on Documentation/Signoffs/ReidCrews-signoff-Location.md
> +![Alt text](https://github.com/lchapman42/Control-Sensing-Wireless-Charging-Robot/blob/reidcrews-signoff-Location/Documentation/Electrical/Schematics/Sources/Position/PositionSensorSchematic2.png)
How is the mega powered?

2023-11-06 18:57 UTC, reidcrews commented on Documentation/Signoffs/ReidCrews-signoff-Location.md
> +![Alt text](https://github.com/lchapman42/Control-Sensing-Wireless-Charging-Robot/blob/reidcrews-signoff-Location/Documentation/Electrical/Schematics/Sources/Position/PositionSensorSchematic2.png)
By Power Distribution Bus,

2023-11-06 18:57 UTC, reidcrews commented on Documentation/Signoffs/ReidCrews-signoff-Location.md
> +![Alt text](https://github.com/lchapman42/Control-Sensing-Wireless-Charging-Robot/blob/reidcrews-signoff-Location/Documentation/Electrical/Schematics/Sources/Position/PositionSensorSchematic2.png)
5 V

2023-11-07 21:51 UTC, n37chen approved these changes

2023-11-08 19:13 UTC, merged